---
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

name: Docker Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        default: 'latest'

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Docker

    steps:
      # https://github.com/marketplace/actions/checkout
      # - name: Build the Docker image
      #   uses: actions/checkout@v4
      #   run: docker build . --file Dockerfile --tag raneto/raneto:latest-$(date +%s)

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/marketplace/actions/docker-login
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          #context: .
          push: true
          tags: "raneto/raneto:${{ github.event.inputs.version }}"